### This file is generated by opam2nix.

self:
let
  lib = self.lib;
  pkgs = self.pkgs;
  selection = self.selection;
  repoPath = self.repoPath;
  repos =
    {
      opam-repository =
        rec {
          fetch =
            {
              owner = "ocaml";
              repo = "opam-repository";
              rev = "11df3a42868b33d2abdcca4a16cd711b5fb12941";
              sha256 = "0p1yjxlspydn6rm29gvkb76f687anvh0snb0df1rayf2jpd8fvj0";
            };
          src = (pkgs.fetchFromGitHub) fetch;
        };
    };
in
{
  format-version = 4;
  inherit repos;
  ocaml-version = "4.14.1";
  selection =
    {
      angstrom =
        {
          pname = "angstrom";
          version = "0.15.0";
          src = pkgs.fetchurl
            {
              url = "https://github.com/inhabitedtype/angstrom/archive/0.15.0.tar.gz";
              sha256 = "01cjjal8vjsm225v9y0q6ixam8k5f821rcr6yix6i9nzs84aq6gi";
            };
          opamInputs =
            {
              inherit (selection) result ocaml-syntax-shims ocaml dune bigstringaf;
            };
          opamSrc = repoPath (repos.opam-repository.src)
            {
              package = "packages/angstrom/angstrom.0.15.0";
              hash = "sha256:07ryik3g3hz79hnfdwxdh2jsw3cmbgygjs7mjdw07p927wkd83k9";
            };
        };
      base =
        {
          pname = "base";
          version = "v0.16.3";
          src = pkgs.fetchurl
            {
              url = "https://github.com/janestreet/base/archive/refs/tags/v0.16.3.tar.gz";
              sha256 = "0g7rrwnd3sb4pcpnvq7hc7dd7rg1gh0axxdhqwjh60dxw81ybycv";
            };
          opamInputs =
            {
              inherit (selection) sexplib0 ocaml dune-configurator dune;
            };
          opamSrc = repoPath (repos.opam-repository.src)
            {
              package = "packages/base/base.v0.16.3";
              hash = "sha256:0agy8qgasnz9wc03nssa38b0k76hbm3s8d11v35ppqxr9qiiwcsx";
            };
        };
      base-bytes =
        {
          pname = "base-bytes";
          version = "base";
          src = null;
          opamInputs = {
            inherit (selection) ocamlfind ocaml;
          };
          opamSrc = repoPath (repos.opam-repository.src)
            {
              package = "packages/base-bytes/base-bytes.base";
              hash = "sha256:0a68lmbf68jgm1i3b59j2sc3ha9yhv4678f9mfwwvczw88prq7l3";
            };
        };
      base-threads =
        {
          pname = "base-threads";
          version = "base";
          src = null;
          opamInputs = { };
          opamSrc = repoPath (repos.opam-repository.src)
            {
              package = "packages/base-threads/base-threads.base";
              hash = "sha256:1c4bpyh61ampjgk5yh3inrgcpf1z1xv0pshn54ycmpn4dyzv0p2x";
            };
        };
      base-unix =
        {
          pname = "base-unix";
          version = "base";
          src = null;
          opamInputs = { };
          opamSrc = repoPath (repos.opam-repository.src)
            {
              package = "packages/base-unix/base-unix.base";
              hash = "sha256:0mpsvb7684g723ylngryh15aqxg3blb7hgmq2fsqjyppr36iyzwg";
            };
        };
      base64 =
        {
          pname = "base64";
          version = "3.5.1";
          src = pkgs.fetchurl
            {
              url = "https://github.com/mirage/ocaml-base64/releases/download/v3.5.1/base64-3.5.1.tbz";
              sha256 = "1vb53ijh098d8x0d5a2c7x9ar2j7vll5k2y0mkkylbyikfjxmznq";
            };
          opamInputs = {
            inherit (selection) ocaml dune;
          };
          opamSrc = repoPath (repos.opam-repository.src)
            {
              package = "packages/base64/base64.3.5.1";
              hash = "sha256:0qw6lbd3fjpdll98ihhwzry3xdd2syr545rnbb8fxffzwkpn7nwa";
            };
        };
      base_bigstring =
        {
          pname = "base_bigstring";
          version = "v0.16.0";
          src = pkgs.fetchurl
            {
              url = "https://ocaml.janestreet.com/ocaml-core/v0.16/files/base_bigstring-v0.16.0.tar.gz";
              sha256 = "1hr6m4zjkyxgiskyiwff8sw1rzz4hy83lhbr6r8psmgsl67vzz0r";
            };
          opamInputs =
            {
              inherit (selection) ppx_jane ocaml int_repr dune base;
            };
          opamSrc = repoPath (repos.opam-repository.src)
            {
              package = "packages/base_bigstring/base_bigstring.v0.16.0";
              hash = "sha256:0lr0pjniwmggq6a46ymm80pslbfvvfj08cfcaj1hf64rwimi2i9m";
            };
        };
      base_quickcheck =
        {
          pname = "base_quickcheck";
          version = "v0.16.0";
          src = pkgs.fetchurl
            {
              url = "https://ocaml.janestreet.com/ocaml-core/v0.16/files/base_quickcheck-v0.16.0.tar.gz";
              sha256 = "0zifdpwjxqlbgcsb6wbq74jfqy8rjfxyd4gqs0ryvki4s9shmy48";
            };
          opamInputs =
            {
              inherit (selection) splittable_random ppxlib ppx_sexp_value
                ppx_sexp_message ppx_let ppx_fields_conv ppx_base ocaml dune base;
            };
          opamSrc = repoPath (repos.opam-repository.src)
            {
              package = "packages/base_quickcheck/base_quickcheck.v0.16.0";
              hash = "sha256:10dj2khzwsm5n5p7jpr3bkgmr619l6plnvdpy2rqbn234x3p0c49";
            };
        };
      bigarray-compat =
        {
          pname = "bigarray-compat";
          version = "1.1.0";
          src = pkgs.fetchurl
            {
              url = "https://github.com/mirage/bigarray-compat/releases/download/v1.1.0/bigarray-compat-1.1.0.tbz";
              sha256 = "1m8q6ywik6h0wrdgv8ah2s617y37n1gdj4qvc86yi12winj6ji23";
            };
          opamInputs = {
            inherit (selection) ocaml dune;
          };
          opamSrc = repoPath (repos.opam-repository.src)
            {
              package = "packages/bigarray-compat/bigarray-compat.1.1.0";
              hash = "sha256:1hq7lmh99p720plkbv1faqqz2xz4ff9g49kkpsryg9ws3ld8ry05";
            };
        };
      bigarray-overlap =
        {
          pname = "bigarray-overlap";
          version = "0.2.1";
          src = pkgs.fetchurl
            {
              url = "https://github.com/dinosaure/overlap/releases/download/v0.2.1/bigarray-overlap-0.2.1.tbz";
              sha256 = "1q363ap89kr2ifswylvpnpfpcrlby95jbagbhdc36kh5f320llig";
            };
          opamInputs =
            {
              inherit (selection) ocaml dune
                conf-pkg-config;
              ocaml-freestanding = selection.ocaml-freestanding or null;
              mirage-xen-posix = selection.mirage-xen-posix or null;
              js_of_ocaml-compiler = selection.js_of_ocaml-compiler or null;
            };
          opamSrc = repoPath (repos.opam-repository.src)
            {
              package = "packages/bigarray-overlap/bigarray-overlap.0.2.1";
              hash = "sha256:198fm0zs39gdx5f6ns7av19jqr9gl60lk8ypi6ymr46s08lq2bjc";
            };
        };
      bigstringaf =
        {
          pname = "bigstringaf";
          version = "0.9.1";
          src = pkgs.fetchurl
            {
              url = "https://github.com/inhabitedtype/bigstringaf/archive/0.9.1.tar.gz";
              sha256 = "02smd8d2iv47r5a150nj3angxfp1vwc5474la1jqp68lsrvr5yc7";
            };
          opamInputs =
            {
              inherit (selection) ocaml dune-configurator dune;
            };
          opamSrc = repoPath (repos.opam-repository.src)
            {
              package = "packages/bigstringaf/bigstringaf.0.9.1";
              hash = "sha256:1f0g6rfnws5pkimpm11pnr8xnq1jw2vhajv6czg3j2n2qndag3a8";
            };
        };
      bin_prot =
        {
          pname = "bin_prot";
          version = "v0.16.0";
          src = pkgs.fetchurl
            {
              url = "https://ocaml.janestreet.com/ocaml-core/v0.16/files/bin_prot-v0.16.0.tar.gz";
              sha256 = "1wd2s38hbsza0xc0gfn22h20xmn62kc4kpkspji6n609v24q1piy";
            };
          opamInputs =
            {
              inherit (selection) ppx_variants_conv ppx_stable_witness
                ppx_sexp_conv ppx_optcomp ppx_fields_conv ppx_custom_printf
                ppx_compare ocaml dune
                base;
              mirage-xen-ocaml = selection.mirage-xen-ocaml or null;
            };
          opamSrc = repoPath (repos.opam-repository.src)
            {
              package = "packages/bin_prot/bin_prot.v0.16.0";
              hash = "sha256:11qww3yl5iprx6jwgwd74p4l84nh9x9a0m33h2ssyy6wqmj7a8r3";
            };
        };
      camlp-streams =
        {
          pname = "camlp-streams";
          version = "5.0.1";
          src = pkgs.fetchurl
            {
              url = "https://github.com/ocaml/camlp-streams/archive/v5.0.1.tar.gz";
              sha256 = "196rn0z2q53f8is5bwln1n5qzipn5bg3wnflnmzlxfz90qjgcwdd";
            };
          opamInputs = {
            inherit (selection) ocaml dune;
          };
          opamSrc = repoPath (repos.opam-repository.src)
            {
              package = "packages/camlp-streams/camlp-streams.5.0.1";
              hash = "sha256:177a68cgm23pryyji88dvn300qz55sl154wfwmzvp8arhs7yg6bn";
            };
        };
      caqti =
        {
          pname = "caqti";
          version = "1.9.0";
          src = pkgs.fetchurl
            {
              url = "https://github.com/paurkedal/ocaml-caqti/releases/download/v1.9.0/caqti-v1.9.0.tbz";
              sha256 = "1icj262f3l186j9bra0cwlpnlzzpfln7y1kl67r58fmgiy281xg1";
            };
          opamInputs =
            {
              inherit (selection) uri ptime ocaml logs dune cppo bigstringaf
                angstrom;
            };
          opamSrc = repoPath (repos.opam-repository.src)
            {
              package = "packages/caqti/caqti.1.9.0";
              hash = "sha256:0c1fis50da64rbdvqcian3yp3y8g237wb5hp4jkz2chlcgml0pld";
            };
        };
      caqti-lwt =
        {
          pname = "caqti-lwt";
          version = "1.9.0";
          src = pkgs.fetchurl
            {
              url = "https://github.com/paurkedal/ocaml-caqti/releases/download/v1.9.0/caqti-v1.9.0.tbz";
              sha256 = "1icj262f3l186j9bra0cwlpnlzzpfln7y1kl67r58fmgiy281xg1";
            };
          opamInputs =
            {
              inherit (selection) ocaml lwt logs dune caqti;
            };
          opamSrc = repoPath (repos.opam-repository.src)
            {
              package = "packages/caqti-lwt/caqti-lwt.1.9.0";
              hash = "sha256:05jamcazv09m51r9pnfqmhhmmi6ysqkv04r6fypqdcjsvjx64ppw";
            };
        };
      conf-libev =
        {
          pname = "conf-libev";
          version = "4-12";
          src = null;
          opamInputs = {
            inherit (selection) ocaml;
          };
          opamSrc = repoPath (repos.opam-repository.src)
            {
              package = "packages/conf-libev/conf-libev.4-12";
              hash = "sha256:15b62x682v5zgybna05wg6mxhxkx1pd2l28db88yhymgv972nfyg";
            };
          buildInputs = [ (pkgs.libev) ];
        };
      conf-libssl =
        {
          pname = "conf-libssl";
          version = "4";
          src = null;
          opamInputs = {
            inherit (selection) conf-pkg-config;
          };
          opamSrc = repoPath (repos.opam-repository.src)
            {
              package = "packages/conf-libssl/conf-libssl.4";
              hash = "sha256:1x6sqj867wny2mc6sb77pfv29fswxmh45cisxlxgfn2ky7rfxqwv";
            };
          buildInputs = [ (pkgs.openssl) ];
        };
      conf-pkg-config =
        {
          pname = "conf-pkg-config";
          version = "3";
          src = null;
          opamInputs = { };
          opamSrc = repoPath (repos.opam-repository.src)
            {
              package = "packages/conf-pkg-config/conf-pkg-config.3";
              hash = "sha256:1prwj03f12qpn0zl20371d2zpzwza0svnilsjmnbgbhqyf8aamqw";
            };
          buildInputs = [ (pkgs.pkgconfig) ];
        };
      core =
        {
          pname = "core";
          version = "v0.16.2";
          src = pkgs.fetchurl
            {
              url = "https://github.com/janestreet/core/archive/refs/tags/v0.16.2.tar.gz";
              sha256 = "1zcrbggb63hqfqz1fn8iajzqjab5bimzvnw4bn502npav05kk8wv";
            };
          opamInputs =
            {
              inherit (selection) variantslib typerep time_now stdio
                splittable_random sexplib ppx_sexp_message ppx_sexp_conv ppx_optcomp
                ppx_jane ppx_inline_test ppx_hash ppx_base ppx_assert ocaml
                jst-config jane-street-headers fieldslib dune bin_prot
                base_quickcheck base_bigstring base;
            };
          opamSrc = repoPath (repos.opam-repository.src)
            {
              package = "packages/core/core.v0.16.2";
              hash = "sha256:0hz2lfzxql2mwkam816zc38d5693byf1bfgvmyihb1zy5zk54jid";
            };
        };
      cppo =
        {
          pname = "cppo";
          version = "1.6.9";
          src = pkgs.fetchurl
            {
              url = "https://github.com/ocaml-community/cppo/archive/v1.6.9.tar.gz";
              sha256 = "0sm2vn5y7w7fyrwkv7f86y4nvs5vsrqy1x2nidy0lcqxq62ns0qn";
            };
          opamInputs =
            {
              inherit (selection) ocaml dune base-unix;
            };
          opamSrc = repoPath (repos.opam-repository.src)
            {
              package = "packages/cppo/cppo.1.6.9";
              hash = "sha256:19i6yqv9lq09v3xw1sfqayh40sihhd4hfyvk9dwz1m5dv1g63xlp";
            };
        };
      csexp =
        {
          pname = "csexp";
          version = "1.5.2";
          src = pkgs.fetchurl
            {
              url = "https://github.com/ocaml-dune/csexp/releases/download/1.5.2/csexp-1.5.2.tbz";
              sha256 = "1zw7fxlhx5mnf09mrhzk0yf3m4bpiii51194j0cs8ya3pc2ds50s";
            };
          opamInputs = {
            inherit (selection) ocaml dune;
          };
          opamSrc = repoPath (repos.opam-repository.src)
            {
              package = "packages/csexp/csexp.1.5.2";
              hash = "sha256:1j22xbli4h2ni6y2a6ghfzdnwx0z5x1nw57hr6nmsdk0ys04a0gs";
            };
        };
      cstruct =
        {
          pname = "cstruct";
          version = "6.2.0";
          src = pkgs.fetchurl
            {
              url = "https://github.com/mirage/ocaml-cstruct/releases/download/v6.2.0/cstruct-6.2.0.tbz";
              sha256 = "0qiyy1h7qsy90hdl01qdsg4rv61f3d5sp8wg2i4q63jqj8rhfy4s";
            };
          opamInputs = {
            inherit (selection) ocaml fmt dune;
          };
          opamSrc = repoPath (repos.opam-repository.src)
            {
              package = "packages/cstruct/cstruct.6.2.0";
              hash = "sha256:0r6dag0mhrs61gyh6pcf888s5npmgwj9rxag1d6a700p866cza7q";
            };
        };
      digestif =
        {
          pname = "digestif";
          version = "1.1.4";
          src = pkgs.fetchurl
            {
              url = "https://github.com/mirage/digestif/releases/download/v1.1.4/digestif-1.1.4.tbz";
              sha256 = "1q8i6lsmmcc9xjbm8kkz5s4bxzm74744bic6c97hba0d1xr3wyf3";
            };
          opamInputs = {
            inherit (selection) ocaml eqaf dune;
          };
          opamSrc = repoPath (repos.opam-repository.src)
            {
              package = "packages/digestif/digestif.1.1.4";
              hash = "sha256:06rvw77j7096mvs6l8if917qi8cljz16m1xng17grlpg0fswjiks";
            };
        };
      dream =
        {
          pname = "dream";
          version = "1.0.0-alpha5";
          src = pkgs.fetchurl
            {
              url = "https://github.com/aantron/dream/releases/download/1.0.0-alpha5/dream-1.0.0-alpha5.tar.gz";
              sha256 = "00arfk3qsd17p94sqgvnndlhr4i86gpcsnrs3wakr2clzxm7zg05";
            };
          opamInputs =
            {
              inherit (selection) yojson uri ssl ptime ocaml multipart_form-lwt
                multipart_form mirage-crypto-rng-lwt mirage-crypto-rng mirage-crypto
                mirage-clock magic-mime lwt_ssl lwt_ppx lwt logs graphql_parser
                graphql-lwt fmt dune dream-pure dream-httpaf cstruct conf-libev
                caqti-lwt caqti camlp-streams bigarray-compat base-unix;
            };
          opamSrc = repoPath (repos.opam-repository.src)
            {
              package = "packages/dream/dream.1.0.0~alpha5";
              hash = "sha256:18819b01l3sx49mfw7rwr6ympkvgkps656wfxdwqd80ifxb2kjm4";
            };
        };
      dream-httpaf =
        {
          pname = "dream-httpaf";
          version = "1.0.0-alpha2";
          src = pkgs.fetchurl
            {
              url = "https://github.com/aantron/dream/releases/download/1.0.0-alpha5/dream-1.0.0-alpha5.tar.gz";
              sha256 = "00arfk3qsd17p94sqgvnndlhr4i86gpcsnrs3wakr2clzxm7zg05";
            };
          opamInputs =
            {
              inherit (selection) ssl result psq ocaml lwt_ssl lwt_ppx lwt ke
                faraday-lwt-unix faraday dune dream-pure digestif bigstringaf base64
                angstrom;
            };
          opamSrc = repoPath (repos.opam-repository.src)
            {
              package = "packages/dream-httpaf/dream-httpaf.1.0.0~alpha2";
              hash = "sha256:14dz2wfn5xsis9aj172wrmgg29k4mgx05p0cc0py1dqzp7606qrp";
            };
        };
      dream-pure =
        {
          pname = "dream-pure";
          version = "1.0.0-alpha2";
          src = pkgs.fetchurl
            {
              url = "https://github.com/aantron/dream/releases/download/1.0.0-alpha4/dream-1.0.0-alpha4.tar.gz";
              sha256 = "045glrnb15k6vv7avg0s002kycynf5cmir3cl6g0ih379mlv6hx1";
            };
          opamInputs =
            {
              inherit (selection) uri ptime ocaml lwt_ppx lwt hmap dune bigstringaf
                base64;
            };
          opamSrc = repoPath (repos.opam-repository.src)
            {
              package = "packages/dream-pure/dream-pure.1.0.0~alpha2";
              hash = "sha256:1fyci212rfljj2glm09wnjzib0ymyw3hrzi6x5qvgw65f4h8xf4q";
            };
        };
      dune =
        {
          pname = "dune";
          version = "3.11.1";
          src = pkgs.fetchurl
            {
              url = "https://github.com/ocaml/dune/releases/download/3.11.1/dune-3.11.1.tbz";
              sha256 = "0w9zxp2hzi4ndiraclv90jm2nycq82xri7dzyc27dbxdml3j6vw6";
            };
          opamInputs =
            {
              inherit (selection) base-unix
                base-threads;
              ocamlfind-secondary = selection.ocamlfind-secondary or null;
              ocaml = selection.ocaml or null;
            };
          opamSrc = repoPath (repos.opam-repository.src)
            {
              package = "packages/dune/dune.3.11.1";
              hash = "sha256:044zsbrg63gjpxfw0bbn0ac8dbg9fnsk3vmi9icy34vbzil97x8k";
            };
        };
      dune-configurator =
        {
          pname = "dune-configurator";
          version = "3.11.1";
          src = pkgs.fetchurl
            {
              url = "https://github.com/ocaml/dune/releases/download/3.11.1/dune-3.11.1.tbz";
              sha256 = "0w9zxp2hzi4ndiraclv90jm2nycq82xri7dzyc27dbxdml3j6vw6";
            };
          opamInputs =
            {
              inherit (selection) ocaml dune csexp base-unix;
            };
          opamSrc = repoPath (repos.opam-repository.src)
            {
              package = "packages/dune-configurator/dune-configurator.3.11.1";
              hash = "sha256:1j5325wx2vj8sx9naafbs2hcpad005qf37skdxdcnrvcmn6bwjf3";
            };
        };
      duration =
        {
          pname = "duration";
          version = "0.2.1";
          src = pkgs.fetchurl
            {
              url = "https://github.com/hannesm/duration/releases/download/v0.2.1/duration-0.2.1.tbz";
              sha256 = "0aqyqzkrkkn33jysq3nmy0l24jyy37wdvlqw286856gvikrw2f67";
            };
          opamInputs = {
            inherit (selection) ocaml dune;
          };
          opamSrc = repoPath (repos.opam-repository.src)
            {
              package = "packages/duration/duration.0.2.1";
              hash = "sha256:1d7922cvnnccck7kr2dss0d922f17nxsqhygszw5hn5xyirldbpy";
            };
        };
      eqaf =
        {
          pname = "eqaf";
          version = "0.9";
          src = pkgs.fetchurl
            {
              url = "https://github.com/mirage/eqaf/releases/download/v0.9/eqaf-0.9.tbz";
              sha256 = "1q6zanrbj0ddrxwhwqdv1223mbk1k5dg0m2qbpwifs5c8sljh3pc";
            };
          opamInputs =
            {
              inherit (selection) ocaml dune cstruct;
            };
          opamSrc = repoPath (repos.opam-repository.src)
            {
              package = "packages/eqaf/eqaf.0.9";
              hash = "sha256:12yfvhy9n7qmfy8z6ppz15s13n9l3n0pqpyqms5kalqwcfnxaf7i";
            };
        };
      faraday =
        {
          pname = "faraday";
          version = "0.8.2";
          src = pkgs.fetchurl
            {
              url = "https://github.com/inhabitedtype/faraday/archive/0.8.2.tar.gz";
              sha256 = "1iiml37sgn28mm0szm4ldqq6fkji4l5368l7dvgafgpx745sj3kj";
            };
          opamInputs =
            {
              inherit (selection) ocaml dune bigstringaf;
            };
          opamSrc = repoPath (repos.opam-repository.src)
            {
              package = "packages/faraday/faraday.0.8.2";
              hash = "sha256:0fpkk78zjbvs6h7cmr7assqibg22b5n1kyjidjv600vn4d44fyk8";
            };
        };
      faraday-lwt =
        {
          pname = "faraday-lwt";
          version = "0.8.2";
          src = pkgs.fetchurl
            {
              url = "https://github.com/inhabitedtype/faraday/archive/0.8.2.tar.gz";
              sha256 = "1iiml37sgn28mm0szm4ldqq6fkji4l5368l7dvgafgpx745sj3kj";
            };
          opamInputs =
            {
              inherit (selection) ocaml lwt faraday dune;
            };
          opamSrc = repoPath (repos.opam-repository.src)
            {
              package = "packages/faraday-lwt/faraday-lwt.0.8.2";
              hash = "sha256:0qrfcvfqbwk5qp2rz99zhjgay823k0vf0wfvpp8b1dpmsn0h0fig";
            };
        };
      faraday-lwt-unix =
        {
          pname = "faraday-lwt-unix";
          version = "0.8.2";
          src = pkgs.fetchurl
            {
              url = "https://github.com/inhabitedtype/faraday/archive/0.8.2.tar.gz";
              sha256 = "1iiml37sgn28mm0szm4ldqq6fkji4l5368l7dvgafgpx745sj3kj";
            };
          opamInputs =
            {
              inherit (selection) ocaml lwt faraday-lwt dune base-unix;
            };
          opamSrc = repoPath (repos.opam-repository.src)
            {
              package = "packages/faraday-lwt-unix/faraday-lwt-unix.0.8.2";
              hash = "sha256:1f3zpi4fri93376alnchi88999vifrlp3ri86ca337pb0c777hlp";
            };
        };
      fieldslib =
        {
          pname = "fieldslib";
          version = "v0.16.0";
          src = pkgs.fetchurl
            {
              url = "https://ocaml.janestreet.com/ocaml-core/v0.16/files/fieldslib-v0.16.0.tar.gz";
              sha256 = "1wdjb5h8rc7gvsy2sdw3bsixq11cwfzqc3mdz9yp86p7b519bi9c";
            };
          opamInputs = {
            inherit (selection) ocaml dune base;
          };
          opamSrc = repoPath (repos.opam-repository.src)
            {
              package = "packages/fieldslib/fieldslib.v0.16.0";
              hash = "sha256:0fgk3vh3g6k7ryy7wqii24cm97444cnpr0qr5jpn04gl22sh6hk6";
            };
        };
      fmt =
        {
          pname = "fmt";
          version = "0.9.0";
          src = pkgs.fetchurl
            {
              url = "https://erratique.ch/software/fmt/releases/fmt-0.9.0.tbz";
              sha256 = "0q8j2in2473xh7k4hfgnppv9qy77f2ih89yp6yhpbp92ba021yzi";
            };
          opamInputs =
            {
              inherit (selection) topkg ocamlfind ocamlbuild
                ocaml;
              cmdliner = selection.cmdliner or null;
              base-unix = selection.base-unix or null;
            };
          opamSrc = repoPath (repos.opam-repository.src)
            {
              package = "packages/fmt/fmt.0.9.0";
              hash = "sha256:1czh5i3i4mkf9xfasji3v7n821qmnnandlklh67ali0x87brldny";
            };
        };
      graphql =
        {
          pname = "graphql";
          version = "0.14.0";
          src = pkgs.fetchurl
            {
              url = "https://github.com/andreas/ocaml-graphql-server/releases/download/0.14.0/graphql-0.14.0.tbz";
              sha256 = "01hwrnps7b8862id6gvm8vkkicg2kxv8l5c2pp5mwdbyw6wzb2xz";
            };
          opamInputs =
            {
              inherit (selection) yojson seq rresult ocaml graphql_parser dune;
            };
          opamSrc = repoPath (repos.opam-repository.src)
            {
              package = "packages/graphql/graphql.0.14.0";
              hash = "sha256:1bm0zm844vcrp63wqp74z6ls5ji74i97fbr7cvdp920i4i0fxpbb";
            };
        };
      graphql-lwt =
        {
          pname = "graphql-lwt";
          version = "0.14.0";
          src = pkgs.fetchurl
            {
              url = "https://github.com/andreas/ocaml-graphql-server/releases/download/0.14.0/graphql-0.14.0.tbz";
              sha256 = "01hwrnps7b8862id6gvm8vkkicg2kxv8l5c2pp5mwdbyw6wzb2xz";
            };
          opamInputs =
            {
              inherit (selection) ocaml lwt graphql dune;
            };
          opamSrc = repoPath (repos.opam-repository.src)
            {
              package = "packages/graphql-lwt/graphql-lwt.0.14.0";
              hash = "sha256:1da1wyynhskv39in621q5z0mjdgxz31f265fjxfysd98ipw1n19q";
            };
        };
      graphql_parser =
        {
          pname = "graphql_parser";
          version = "0.14.0";
          src = pkgs.fetchurl
            {
              url = "https://github.com/andreas/ocaml-graphql-server/releases/download/0.14.0/graphql-0.14.0.tbz";
              sha256 = "01hwrnps7b8862id6gvm8vkkicg2kxv8l5c2pp5mwdbyw6wzb2xz";
            };
          opamInputs =
            {
              inherit (selection) re ocaml menhir fmt dune;
            };
          opamSrc = repoPath (repos.opam-repository.src)
            {
              package = "packages/graphql_parser/graphql_parser.0.14.0";
              hash = "sha256:1x1a9wzp4q7pvcxs7s8lljzklinzj7l103n7kdp5jg229h0vqjnx";
            };
        };
      hmap =
        {
          pname = "hmap";
          version = "0.8.1";
          src = pkgs.fetchurl
            {
              url = "http://erratique.ch/software/hmap/releases/hmap-0.8.1.tbz";
              sha256 = "10xyjy4ab87z7jnghy0wnla9wrmazgyhdwhr4hdmxxdn28dxn03a";
            };
          opamInputs =
            {
              inherit (selection) topkg ocamlfind ocamlbuild ocaml;
            };
          opamSrc = repoPath (repos.opam-repository.src)
            {
              package = "packages/hmap/hmap.0.8.1";
              hash = "sha256:19yc0fm5c0wzxyrwfy3bcb6yh3hbgwrhhh94ggzjs7di8vv9bkv1";
            };
        };
      int_repr =
        {
          pname = "int_repr";
          version = "v0.16.0";
          src = pkgs.fetchurl
            {
              url = "https://ocaml.janestreet.com/ocaml-core/v0.16/files/int_repr-v0.16.0.tar.gz";
              sha256 = "0xphnqh3cp1qjlbq08ss57q6dhra2g3n090nh7zp3qgy5wk5cbqk";
            };
          opamInputs =
            {
              inherit (selection) ppx_jane ocaml dune base;
            };
          opamSrc = repoPath (repos.opam-repository.src)
            {
              package = "packages/int_repr/int_repr.v0.16.0";
              hash = "sha256:0yrd9nrxm8x1qf30ba16cn3g7w3wlzw2ibhdshcbbknshy145bkl";
            };
        };
      jane-street-headers =
        {
          pname = "jane-street-headers";
          version = "v0.16.0";
          src = pkgs.fetchurl
            {
              url = "https://ocaml.janestreet.com/ocaml-core/v0.16/files/jane-street-headers-v0.16.0.tar.gz";
              sha256 = "1sk0scvi657c0jvmdcgi2nmd4aa8qq0vc3q121xli5dlxsgl0vc7";
            };
          opamInputs = {
            inherit (selection) ocaml dune;
          };
          opamSrc = repoPath (repos.opam-repository.src)
            {
              package = "packages/jane-street-headers/jane-street-headers.v0.16.0";
              hash = "sha256:04clgm4x0zbk9v5vs1v068i8ww48q91g1wa2kqxv0i63hawqc8i7";
            };
        };
      jst-config =
        {
          pname = "jst-config";
          version = "v0.16.0";
          src = pkgs.fetchurl
            {
              url = "https://ocaml.janestreet.com/ocaml-core/v0.16/files/jst-config-v0.16.0.tar.gz";
              sha256 = "0nyr2hyff4s0qq66095p223w9705msdlzmcs17f8r1l2hmnxbsps";
            };
          opamInputs =
            {
              inherit (selection) ppx_assert ocaml dune-configurator dune base;
            };
          opamSrc = repoPath (repos.opam-repository.src)
            {
              package = "packages/jst-config/jst-config.v0.16.0";
              hash = "sha256:1yvn8w6cx3xlx9aiy8zsqg26v59kcdq019lsgz9ybyhn6bj3fjpd";
            };
        };
      ke =
        {
          pname = "ke";
          version = "0.6";
          src = pkgs.fetchurl
            {
              url = "https://github.com/mirage/ke/releases/download/v0.6/ke-0.6.tbz";
              sha256 = "0193cw6srkbjmsslr1bzcjd2c24jzw86cwsrfyqh82r0w83p48b1";
            };
          opamInputs = {
            inherit (selection) ocaml fmt dune;
          };
          opamSrc = repoPath (repos.opam-repository.src)
            {
              package = "packages/ke/ke.0.6";
              hash = "sha256:0d5xgsihg6nxz845pk80p9x5j0mnk9ajgmxkx2rp1xxpnpmdi38i";
            };
        };
      logs =
        {
          pname = "logs";
          version = "0.7.0";
          src = pkgs.fetchurl
            {
              url = "https://erratique.ch/software/logs/releases/logs-0.7.0.tbz";
              sha256 = "1jnmd675wmsmdwyb5mx5b0ac66g4c6gpv5s4mrx2j6pb0wla1x46";
            };
          opamInputs =
            {
              inherit (selection) topkg ocamlfind ocamlbuild
                ocaml;
              lwt = selection.lwt or null;
              js_of_ocaml = selection.js_of_ocaml or null;
              fmt = selection.fmt or null;
              cmdliner = selection.cmdliner or null;
              base-threads = selection.base-threads or null;
            };
          opamSrc = repoPath (repos.opam-repository.src)
            {
              package = "packages/logs/logs.0.7.0";
              hash = "sha256:0pys6d25bghrwvwd4gflib2yyp5fvdy0rkivbdyli5dmp5j35a3n";
            };
        };
      lwt =
        {
          pname = "lwt";
          version = "5.7.0";
          src = pkgs.fetchurl
            {
              url = "https://github.com/ocsigen/lwt/archive/refs/tags/5.7.0.tar.gz";
              sha256 = "11dpr0aprqqjgb2n4j4czpw3l0bc8dzy1jqmp2qz3xkih31k241p";
            };
          opamInputs =
            {
              inherit (selection) ocplib-endian ocaml dune-configurator dune
                cppo;
              conf-libev = selection.conf-libev or null;
              base-unix = selection.base-unix or null;
              base-threads = selection.base-threads or null;
            };
          opamSrc = repoPath (repos.opam-repository.src)
            {
              package = "packages/lwt/lwt.5.7.0";
              hash = "sha256:1fpvcmvrkwaz6w5rshgpw37n10dz9js68i553mmjs1g2g6wdpq73";
            };
        };
      lwt_ppx =
        {
          pname = "lwt_ppx";
          version = "2.1.0";
          src = pkgs.fetchurl
            {
              url = "https://github.com/ocsigen/lwt/archive/5.6.0.tar.gz";
              sha256 = "1qg5wjlmrnd295lljncr1db1rw50pr13wmak3rcg92n9wd1fzm0v";
            };
          opamInputs =
            {
              inherit (selection) ppxlib ocaml lwt dune;
            };
          opamSrc = repoPath (repos.opam-repository.src)
            {
              package = "packages/lwt_ppx/lwt_ppx.2.1.0";
              hash = "sha256:09kc2bwmqq41983xivild7az3s62nrhp62iinvc2b6lpcldzvqqc";
            };
        };
      lwt_ssl =
        {
          pname = "lwt_ssl";
          version = "1.2.0";
          src = pkgs.fetchurl
            {
              url = "https://github.com/ocsigen/lwt_ssl/releases/download/1.2.0/lwt_ssl-1.2.0.tbz";
              sha256 = "0xwsi140ahap2d8ncc443ycvmjvdnc40lx7jqghpgwzcgb90l0mk";
            };
          opamInputs =
            {
              inherit (selection) ssl ocaml lwt dune base-unix;
            };
          opamSrc = repoPath (repos.opam-repository.src)
            {
              package = "packages/lwt_ssl/lwt_ssl.1.2.0";
              hash = "sha256:1dqqxrzzzdy3y83l0jqdn1zycml80wf0sq4yq58i0zhcjyl7jqcv";
            };
        };
      magic-mime =
        {
          pname = "magic-mime";
          version = "1.3.1";
          src = pkgs.fetchurl
            {
              url = "https://github.com/mirage/ocaml-magic-mime/releases/download/v1.3.1/magic-mime-1.3.1.tbz";
              sha256 = "021vy409qq0gzsn4kzr1lvlsax9dcy3y6mwfqpx1xfjxc81ls8z0";
            };
          opamInputs = {
            inherit (selection) ocaml dune;
          };
          opamSrc = repoPath (repos.opam-repository.src)
            {
              package = "packages/magic-mime/magic-mime.1.3.1";
              hash = "sha256:0f9nbbdgz22qv8l8sgss1ky9h1smywg74x4ivn95jfbf95mvrmnv";
            };
        };
      menhir =
        {
          pname = "menhir";
          version = "20230608";
          src = pkgs.fetchurl
            {
              url = "https://gitlab.inria.fr/fpottier/menhir/-/archive/20230608/archive.tar.gz";
              sha256 = "13mb862c20m1q7vjsa5lgqj3w6b0xhj8ckjyk524wrc4i0s1jzix";
            };
          opamInputs =
            {
              inherit (selection) ocaml menhirSdk menhirLib dune;
            };
          opamSrc = repoPath (repos.opam-repository.src)
            {
              package = "packages/menhir/menhir.20230608";
              hash = "sha256:12s2spwi94fnx51w0sr8jvplazjd6ss4hxn4zn763arcwb9vd223";
            };
        };
      menhirLib =
        {
          pname = "menhirLib";
          version = "20230608";
          src = pkgs.fetchurl
            {
              url = "https://gitlab.inria.fr/fpottier/menhir/-/archive/20230608/archive.tar.gz";
              sha256 = "13mb862c20m1q7vjsa5lgqj3w6b0xhj8ckjyk524wrc4i0s1jzix";
            };
          opamInputs = {
            inherit (selection) ocaml dune;
          };
          opamSrc = repoPath (repos.opam-repository.src)
            {
              package = "packages/menhirLib/menhirLib.20230608";
              hash = "sha256:0s2m697pd1hnmakqrgb2gh1wyaj0ffv402kfnrj9pkdffwbm5v53";
            };
        };
      menhirSdk =
        {
          pname = "menhirSdk";
          version = "20230608";
          src = pkgs.fetchurl
            {
              url = "https://gitlab.inria.fr/fpottier/menhir/-/archive/20230608/archive.tar.gz";
              sha256 = "13mb862c20m1q7vjsa5lgqj3w6b0xhj8ckjyk524wrc4i0s1jzix";
            };
          opamInputs = {
            inherit (selection) ocaml dune;
          };
          opamSrc = repoPath (repos.opam-repository.src)
            {
              package = "packages/menhirSdk/menhirSdk.20230608";
              hash = "sha256:1cfbrwn1y33x69cpfmbmfk8gni1yjd3nr85g20cksjyp6ssxjkw0";
            };
        };
      mirage-clock =
        {
          pname = "mirage-clock";
          version = "4.2.0";
          src = pkgs.fetchurl
            {
              url = "https://github.com/mirage/mirage-clock/releases/download/v4.2.0/mirage-clock-4.2.0.tbz";
              sha256 = "0iwqi2381fbi3jlcw424dbhjs4fpisw7qpqzfjx7jg72bdfx25zs";
            };
          opamInputs = {
            inherit (selection) ocaml dune;
          };
          opamSrc = repoPath (repos.opam-repository.src)
            {
              package = "packages/mirage-clock/mirage-clock.4.2.0";
              hash = "sha256:17zha0ciapnnp83n1mj8nw98pm4m4s0hmbhrs3z6ymllfb70s05q";
            };
        };
      mirage-crypto =
        {
          pname = "mirage-crypto";
          version = "0.11.2";
          src = pkgs.fetchurl
            {
              url = "https://github.com/mirage/mirage-crypto/releases/download/v0.11.2/mirage-crypto-0.11.2.tbz";
              sha256 = "0r7pxlqz5x3cc8a1cwnh0phhlzqygh9h7k0k4mh4ld6wy2vprffn";
            };
          opamInputs =
            {
              inherit (selection) ocaml eqaf dune-configurator dune cstruct;
            };
          opamSrc = repoPath (repos.opam-repository.src)
            {
              package = "packages/mirage-crypto/mirage-crypto.0.11.2";
              hash = "sha256:1h8fm7qvnj3bw1kkkvb1gskpkmy2qvz1hcjyixwaiqpdz9b4wfsq";
            };
        };
      mirage-crypto-rng =
        {
          pname = "mirage-crypto-rng";
          version = "0.11.2";
          src = pkgs.fetchurl
            {
              url = "https://github.com/mirage/mirage-crypto/releases/download/v0.11.2/mirage-crypto-0.11.2.tbz";
              sha256 = "0r7pxlqz5x3cc8a1cwnh0phhlzqygh9h7k0k4mh4ld6wy2vprffn";
            };
          opamInputs =
            {
              inherit (selection) ocaml mirage-crypto logs duration
                dune-configurator dune cstruct;
            };
          opamSrc = repoPath (repos.opam-repository.src)
            {
              package = "packages/mirage-crypto-rng/mirage-crypto-rng.0.11.2";
              hash = "sha256:0vlpwcywbvgxf8y17rlnsck43zv4ga0qvdjn1wd6h52bw48avx9s";
            };
        };
      mirage-crypto-rng-lwt =
        {
          pname = "mirage-crypto-rng-lwt";
          version = "0.11.2";
          src = pkgs.fetchurl
            {
              url = "https://github.com/mirage/mirage-crypto/releases/download/v0.11.2/mirage-crypto-0.11.2.tbz";
              sha256 = "0r7pxlqz5x3cc8a1cwnh0phhlzqygh9h7k0k4mh4ld6wy2vprffn";
            };
          opamInputs =
            {
              inherit (selection) ocaml mtime mirage-crypto-rng mirage-crypto lwt
                logs duration dune;
            };
          opamSrc = repoPath (repos.opam-repository.src)
            {
              package = "packages/mirage-crypto-rng-lwt/mirage-crypto-rng-lwt.0.11.2";
              hash = "sha256:07njfmhas09a4202891phcdwc2y1b0zczcxa9mk91rbfihcgbvch";
            };
        };
      mtime =
        {
          pname = "mtime";
          version = "2.0.0";
          src = pkgs.fetchurl
            {
              url = "https://erratique.ch/software/mtime/releases/mtime-2.0.0.tbz";
              sha256 = "1ss4w3qxsfp51d88r0j7dzqs05dbb1xdx11hn1jl9cvd03ma0g9z";
            };
          opamInputs =
            {
              inherit (selection) topkg ocamlfind ocamlbuild ocaml;
            };
          opamSrc = repoPath (repos.opam-repository.src)
            {
              package = "packages/mtime/mtime.2.0.0";
              hash = "sha256:1q4nd8xpl3bqc1avxrkw4gfrk00xw9r4k1xdzavjdkqd2b5szl89";
            };
        };
      multipart_form =
        {
          pname = "multipart_form";
          version = "0.5.0";
          src = pkgs.fetchurl
            {
              url = "https://github.com/dinosaure/multipart_form/releases/download/v0.5.0/multipart_form-0.5.0.tbz";
              sha256 = "0r4am2ba59kp61my6lifc436wxmnizxwsb6k7cdvlwr81qf6r8x8";
            };
          opamInputs =
            {
              inherit (selection) uutf unstrctrd prettym pecu ocaml logs ke fmt
                dune bigstringaf base64 angstrom;
            };
          opamSrc = repoPath (repos.opam-repository.src)
            {
              package = "packages/multipart_form/multipart_form.0.5.0";
              hash = "sha256:1r3bv14jp5hcxpr49465djmmlljgqgl52f35pyiwd9fp5671lykq";
            };
        };
      multipart_form-lwt =
        {
          pname = "multipart_form-lwt";
          version = "0.5.0";
          src = pkgs.fetchurl
            {
              url = "https://github.com/dinosaure/multipart_form/releases/download/v0.5.0/multipart_form-0.5.0.tbz";
              sha256 = "0r4am2ba59kp61my6lifc436wxmnizxwsb6k7cdvlwr81qf6r8x8";
            };
          opamInputs =
            {
              inherit (selection) ocaml multipart_form lwt ke dune bigstringaf
                angstrom;
            };
          opamSrc = repoPath (repos.opam-repository.src)
            {
              package = "packages/multipart_form-lwt/multipart_form-lwt.0.5.0";
              hash = "sha256:02x6if4x5y0iva10m30cz02jdh8xz7235arxigfv2ys3md7vf1bw";
            };
        };
      myPro =
        {
          pname = "myPro";
          version = "development";
          src = self.directSrc "myPro";
          opamInputs =
            {
              inherit (selection) tyxml ppx_inline_test ocaml dune dream core;
            };
          opamSrc = "myPro.opam";
        };
      num =
        {
          pname = "num";
          version = "1.4";
          src = pkgs.fetchurl
            {
              url = "https://github.com/ocaml/num/archive/v1.4.tar.gz";
              sha256 = "090gl27g84r3s2b12vgkz8fp269jqlrhx4lpg7008yviisv8hl01";
            };
          opamInputs = {
            inherit (selection) ocamlfind ocaml;
          };
          opamSrc = repoPath (repos.opam-repository.src)
            {
              package = "packages/num/num.1.4";
              hash = "sha256:0sz340iwmhl52zv76lx4r21d1c1s8hpjpcb60c3fwikhfcwx2573";
            };
        };
      ocaml =
        {
          pname = "ocaml";
          version = "4.14.1";
          src = null;
          opamInputs =
            {
              inherit (selection)
                ocaml-config;
              ocaml-variants = selection.ocaml-variants or null;
              ocaml-system = selection.ocaml-system or null;
              ocaml-base-compiler = selection.ocaml-base-compiler or null;
            };
          opamSrc = repoPath (repos.opam-repository.src)
            {
              package = "packages/ocaml/ocaml.4.14.1";
              hash = "sha256:16yvyr4nxcpvqp8w7wfhh9rkg2hl4ck3f64fw8kkgx7w2crcp8di";
            };
        };
      ocaml-base-compiler =
        {
          pname = "ocaml-base-compiler";
          version = "4.14.1";
          src = pkgs.fetchurl
            {
              url = "https://github.com/ocaml/ocaml/archive/4.14.1.tar.gz";
              sha256 = "0a5h8m8jliw0pf9xwbsnhp534x2qirc1qf3lkmnzpg5ry3k0cq3p";
            };
          opamInputs = { };
          opamSrc = repoPath (repos.opam-repository.src)
            {
              package = "packages/ocaml-base-compiler/ocaml-base-compiler.4.14.1";
              hash = "sha256:1kpxp8pd4qw0imw3yxqk2m7fchb12b90nxgmqafha8f77qg6a0jw";
            };
        };
      ocaml-compiler-libs =
        {
          pname = "ocaml-compiler-libs";
          version = "v0.12.4";
          src = pkgs.fetchurl
            {
              url = "https://github.com/janestreet/ocaml-compiler-libs/releases/download/v0.12.4/ocaml-compiler-libs-v0.12.4.tbz";
              sha256 = "0q3pl20pkx410gw9g4m26qq6dmzi9qan2dqlga6c2ifc6pnckjaf";
            };
          opamInputs = {
            inherit (selection) ocaml dune;
          };
          opamSrc = repoPath (repos.opam-repository.src)
            {
              package = "packages/ocaml-compiler-libs/ocaml-compiler-libs.v0.12.4";
              hash = "sha256:1blynia10j8vyj559kcvc7ic69zq6qjjn092fcsjzfw6czd8ya2c";
            };
        };
      ocaml-config =
        {
          pname = "ocaml-config";
          version = "2";
          src = null;
          opamInputs =
            {
              ocaml-variants = selection.ocaml-variants or null;
              ocaml-system = selection.ocaml-system or null;
              ocaml-base-compiler = selection.ocaml-base-compiler or null;
            };
          opamSrc = repoPath (repos.opam-repository.src)
            {
              package = "packages/ocaml-config/ocaml-config.2";
              hash = "sha256:0h0hgqq9mbywvqygppfdc50gf9ss8a97l4dgsv3hszmzh6gglgrg";
            };
        };
      ocaml-syntax-shims =
        {
          pname = "ocaml-syntax-shims";
          version = "1.0.0";
          src = pkgs.fetchurl
            {
              url = "https://github.com/ocaml-ppx/ocaml-syntax-shims/releases/download/1.0.0/ocaml-syntax-shims-1.0.0.tbz";
              sha256 = "1j7848khli4p7j8i2kmnvhdnhcwhy3zgdpf5ds5ic30ax69y3cl9";
            };
          opamInputs = {
            inherit (selection) ocaml dune;
          };
          opamSrc = repoPath (repos.opam-repository.src)
            {
              package = "packages/ocaml-syntax-shims/ocaml-syntax-shims.1.0.0";
              hash = "sha256:0qnm1db0298yqcn6j9fmb0l4gr5nhcar8plskj39917invyamgd2";
            };
        };
      ocamlbuild =
        {
          pname = "ocamlbuild";
          version = "0.14.2";
          src = pkgs.fetchurl
            {
              url = "https://github.com/ocaml/ocamlbuild/archive/refs/tags/0.14.2.tar.gz";
              sha256 = "1ccihx2jnk3nsprx2w2kckqqq0bd0skq9i9sm01cg53p0fvdmlk2";
            };
          opamInputs = {
            inherit (selection) ocaml;
          };
          opamSrc = repoPath (repos.opam-repository.src)
            {
              package = "packages/ocamlbuild/ocamlbuild.0.14.2";
              hash = "sha256:0l3lc0z5bzlmsndqv8ylwwzq0p2idzkbwmrrsfkngxh3kls2c5xy";
            };
        };
      ocamlfind =
        {
          pname = "ocamlfind";
          version = "1.9.6";
          src = pkgs.fetchurl
            {
              url = "http://download.camlcity.org/download/findlib-1.9.6.tar.gz";
              sha256 = "18ih56m5z13z5zla7wdrin4y1bdz7pwpjn7znmnn0sz1k8krdy9d";
            };
          opamInputs =
            {
              inherit (selection) ocaml;
              graphics = selection.graphics or null;
            };
          opamSrc = repoPath (repos.opam-repository.src)
            {
              package = "packages/ocamlfind/ocamlfind.1.9.6";
              hash = "sha256:1qs30vvj6mbrrgaxy54kw8zqqghxaywygyhspzhpdkwkl98j3y76";
            };
        };
      ocplib-endian =
        {
          pname = "ocplib-endian";
          version = "1.2";
          src = pkgs.fetchurl
            {
              url = "https://github.com/OCamlPro/ocplib-endian/archive/refs/tags/1.2.tar.gz";
              sha256 = "085kskr0cxcnv2d62n3jq1r273p7giisy56zfl26mm7amvl79blp";
            };
          opamInputs =
            {
              inherit (selection) ocaml dune cppo base-bytes;
            };
          opamSrc = repoPath (repos.opam-repository.src)
            {
              package = "packages/ocplib-endian/ocplib-endian.1.2";
              hash = "sha256:1jldvb471gyhkrzwfvqg722l3a8dc37hhhyas66skjzfmqyi2pnh";
            };
        };
      parsexp =
        {
          pname = "parsexp";
          version = "v0.16.0";
          src = pkgs.fetchurl
            {
              url = "https://ocaml.janestreet.com/ocaml-core/v0.16/files/parsexp-v0.16.0.tar.gz";
              sha256 = "04jywn2q3c4z2xla59qvr0i0bq3zv1p2ghzrp1fai4b1iqn5gqmn";
            };
          opamInputs =
            {
              inherit (selection) sexplib0 ocaml dune;
            };
          opamSrc = repoPath (repos.opam-repository.src)
            {
              package = "packages/parsexp/parsexp.v0.16.0";
              hash = "sha256:0rmgxgyd9s1600936l50a1b7xy64yhwk0jjzglzmpvikw2q9dl2x";
            };
        };
      pecu =
        {
          pname = "pecu";
          version = "0.6";
          src = pkgs.fetchurl
            {
              url = "https://github.com/mirage/pecu/releases/download/v0.6/pecu-v0.6.tbz";
              sha256 = "1iz5jj9lyl1pah8dfni4wv0qml0ir5zknv4zhw7v50sc8kdbglm9";
            };
          opamInputs = {
            inherit (selection) ocaml dune;
          };
          opamSrc = repoPath (repos.opam-repository.src)
            {
              package = "packages/pecu/pecu.0.6";
              hash = "sha256:1h3k00rxhhs31q2inxrypjj8dk3qhnn0bz6xlj3p5hs92frww3s3";
            };
        };
      ppx_assert =
        {
          pname = "ppx_assert";
          version = "v0.16.0";
          src = pkgs.fetchurl
            {
              url = "https://ocaml.janestreet.com/ocaml-core/v0.16/files/ppx_assert-v0.16.0.tar.gz";
              sha256 = "1m9zi1ljdv31afgmi7cfbbgsvl6xhbvg4n69298ivsr730j6xp2p";
            };
          opamInputs =
            {
              inherit (selection) ppxlib ppx_sexp_conv ppx_here ppx_compare
                ppx_cold ocaml dune base;
            };
          opamSrc = repoPath (repos.opam-repository.src)
            {
              package = "packages/ppx_assert/ppx_assert.v0.16.0";
              hash = "sha256:06mgc0vf5xxzpavrwfimy4m4hn22pil0nbvabz1q0wbhzslb2n70";
            };
        };
      ppx_base =
        {
          pname = "ppx_base";
          version = "v0.16.0";
          src = pkgs.fetchurl
            {
              url = "https://ocaml.janestreet.com/ocaml-core/v0.16/files/ppx_base-v0.16.0.tar.gz";
              sha256 = "18v9jlykzf9vmf4c817mxl6d3gqy6mx31ksnzai64cix2mimg0v4";
            };
          opamInputs =
            {
              inherit (selection) ppxlib ppx_sexp_conv ppx_hash ppx_globalize
                ppx_enumerate ppx_compare ppx_cold ocaml dune;
            };
          opamSrc = repoPath (repos.opam-repository.src)
            {
              package = "packages/ppx_base/ppx_base.v0.16.0";
              hash = "sha256:1g513s531vrrvz4s3cnivrxl5zyl1b848m1v0dpdqd3d795hk7sf";
            };
        };
      ppx_bench =
        {
          pname = "ppx_bench";
          version = "v0.16.0";
          src = pkgs.fetchurl
            {
              url = "https://ocaml.janestreet.com/ocaml-core/v0.16/files/ppx_bench-v0.16.0.tar.gz";
              sha256 = "07bnf528mm7b097jrxc23dnay2nhan18h0gshmb14f6bnhjzq1z3";
            };
          opamInputs =
            {
              inherit (selection) ppxlib ppx_inline_test ocaml dune;
            };
          opamSrc = repoPath (repos.opam-repository.src)
            {
              package = "packages/ppx_bench/ppx_bench.v0.16.0";
              hash = "sha256:1ddibn9hkrh53rlqgq4zzl34da590nbn9j4yrvmy4rkklp7iwyhf";
            };
        };
      ppx_bin_prot =
        {
          pname = "ppx_bin_prot";
          version = "v0.16.0";
          src = pkgs.fetchurl
            {
              url = "https://ocaml.janestreet.com/ocaml-core/v0.16/files/ppx_bin_prot-v0.16.0.tar.gz";
              sha256 = "0q9vbjy4473cm1z5jk705wxhnl1cha1nf6aqlf52zwapcdynwj4l";
            };
          opamInputs =
            {
              inherit (selection) ppxlib ppx_here ocaml dune bin_prot base;
            };
          opamSrc = repoPath (repos.opam-repository.src)
            {
              package = "packages/ppx_bin_prot/ppx_bin_prot.v0.16.0";
              hash = "sha256:1gvhqcj8y650g6khgkjiw8p0i8a65nfswiq05swj38jn47xjc8ch";
            };
        };
      ppx_cold =
        {
          pname = "ppx_cold";
          version = "v0.16.0";
          src = pkgs.fetchurl
            {
              url = "https://ocaml.janestreet.com/ocaml-core/v0.16/files/ppx_cold-v0.16.0.tar.gz";
              sha256 = "1nm4d8p26mg3yf9vaaw5jspdi4mq2q6bwd5fv13a46jh7dcdnfw0";
            };
          opamInputs =
            {
              inherit (selection) ppxlib ocaml dune base;
            };
          opamSrc = repoPath (repos.opam-repository.src)
            {
              package = "packages/ppx_cold/ppx_cold.v0.16.0";
              hash = "sha256:1p8gk7scm9rxlxkwkksqnvkpjgva7l9pnn4k6bdpwpdlzjr7qgwa";
            };
        };
      ppx_compare =
        {
          pname = "ppx_compare";
          version = "v0.16.0";
          src = pkgs.fetchurl
            {
              url = "https://ocaml.janestreet.com/ocaml-core/v0.16/files/ppx_compare-v0.16.0.tar.gz";
              sha256 = "1ai6iz2g8sla5jbqr7n34aw7s5n0cbcqp6w7d95nrpk25s2xvhbs";
            };
          opamInputs =
            {
              inherit (selection) ppxlib ocaml dune base;
            };
          opamSrc = repoPath (repos.opam-repository.src)
            {
              package = "packages/ppx_compare/ppx_compare.v0.16.0";
              hash = "sha256:0fd2c5xg9l531zbr0d90z8sl51zqpxjbgdv645zzvnvx5nkyca6w";
            };
        };
      ppx_custom_printf =
        {
          pname = "ppx_custom_printf";
          version = "v0.16.0";
          src = pkgs.fetchurl
            {
              url = "https://ocaml.janestreet.com/ocaml-core/v0.16/files/ppx_custom_printf-v0.16.0.tar.gz";
              sha256 = "19m1cj1310c0j0bya3igclyzyg4b20p2161ha2zjlwc1gfdn6q91";
            };
          opamInputs =
            {
              inherit (selection) ppxlib ppx_sexp_conv ocaml dune base;
            };
          opamSrc = repoPath (repos.opam-repository.src)
            {
              package = "packages/ppx_custom_printf/ppx_custom_printf.v0.16.0";
              hash = "sha256:1kmjrnsmb5hnwishvlz6mra7f7g6xj8b4ckspmv0caicm5i8mf1i";
            };
        };
      ppx_derivers =
        {
          pname = "ppx_derivers";
          version = "1.2.1";
          src = pkgs.fetchurl
            {
              url = "https://github.com/ocaml-ppx/ppx_derivers/archive/1.2.1.tar.gz";
              sha256 = "159vqy616ni18mn0dlv8c2y4h7mb4hahwjn53yrr59yyhzhmwndn";
            };
          opamInputs = {
            inherit (selection) ocaml dune;
          };
          opamSrc = repoPath (repos.opam-repository.src)
            {
              package = "packages/ppx_derivers/ppx_derivers.1.2.1";
              hash = "sha256:1hj1ina0n7pgz16mrvijczapw75pd0hif0i18dpw7d1fyg2qr8py";
            };
        };
      ppx_disable_unused_warnings =
        {
          pname = "ppx_disable_unused_warnings";
          version = "v0.16.0";
          src = pkgs.fetchurl
            {
              url = "https://ocaml.janestreet.com/ocaml-core/v0.16/files/ppx_disable_unused_warnings-v0.16.0.tar.gz";
              sha256 = "1rwq8b78ykv8c07nv44g3c0k18wba1bdvvw38srlxy7483w8zl9z";
            };
          opamInputs =
            {
              inherit (selection) ppxlib ocaml dune base;
            };
          opamSrc = repoPath (repos.opam-repository.src)
            {
              package = "packages/ppx_disable_unused_warnings/ppx_disable_unused_warnings.v0.16.0";
              hash = "sha256:1lrr4pyphrg17mrchw2syv627vnvd83l4vyvfkbhwiqfw8xznlz3";
            };
        };
      ppx_enumerate =
        {
          pname = "ppx_enumerate";
          version = "v0.16.0";
          src = pkgs.fetchurl
            {
              url = "https://ocaml.janestreet.com/ocaml-core/v0.16/files/ppx_enumerate-v0.16.0.tar.gz";
              sha256 = "0lwrxx02shaskn810qba4a7592nd8lkxflgd90ywdi4sdmfn6ci8";
            };
          opamInputs =
            {
              inherit (selection) ppxlib ocaml dune base;
            };
          opamSrc = repoPath (repos.opam-repository.src)
            {
              package = "packages/ppx_enumerate/ppx_enumerate.v0.16.0";
              hash = "sha256:1305lmn66s3ncslsnjswhnc08gs979zh6j62znb78sx99p0af3gk";
            };
        };
      ppx_expect =
        {
          pname = "ppx_expect";
          version = "v0.16.0";
          src = pkgs.fetchurl
            {
              url = "https://ocaml.janestreet.com/ocaml-core/v0.16/files/ppx_expect-v0.16.0.tar.gz";
              sha256 = "0g229sjb2ps1pz3gb21d0xfyg3xja44l91d6ma57axnmw855lyg0";
            };
          opamInputs =
            {
              inherit (selection) stdio re ppxlib ppx_inline_test ppx_here ocaml
                dune base;
            };
          opamSrc = repoPath (repos.opam-repository.src)
            {
              package = "packages/ppx_expect/ppx_expect.v0.16.0";
              hash = "sha256:18saysdmz9mbppp8d0m55gz423j48djyhcay5s73h64i3xsi89jh";
            };
        };
      ppx_fields_conv =
        {
          pname = "ppx_fields_conv";
          version = "v0.16.0";
          src = pkgs.fetchurl
            {
              url = "https://ocaml.janestreet.com/ocaml-core/v0.16/files/ppx_fields_conv-v0.16.0.tar.gz";
              sha256 = "160qqvgq8h6vr9qcm159ddknwcgi9w1yg4d74d31212jifrzm65h";
            };
          opamInputs =
            {
              inherit (selection) ppxlib ocaml fieldslib dune base;
            };
          opamSrc = repoPath (repos.opam-repository.src)
            {
              package = "packages/ppx_fields_conv/ppx_fields_conv.v0.16.0";
              hash = "sha256:1bdls3lw4qbig3wxbhdph4dw50dgvqd6gv03qaxc3y9xrjmyg1r6";
            };
        };
      ppx_fixed_literal =
        {
          pname = "ppx_fixed_literal";
          version = "v0.16.0";
          src = pkgs.fetchurl
            {
              url = "https://ocaml.janestreet.com/ocaml-core/v0.16/files/ppx_fixed_literal-v0.16.0.tar.gz";
              sha256 = "0fc392g7hms05iw4s58d0p2bkhh7insqyfp0lswrsgmcz3aa7ld7";
            };
          opamInputs =
            {
              inherit (selection) ppxlib ocaml dune base;
            };
          opamSrc = repoPath (repos.opam-repository.src)
            {
              package = "packages/ppx_fixed_literal/ppx_fixed_literal.v0.16.0";
              hash = "sha256:13kmy39ajv334zagf0gpl6xapan2fw27kmsbm05b0lbrfd1mb465";
            };
        };
      ppx_globalize =
        {
          pname = "ppx_globalize";
          version = "v0.16.0";
          src = pkgs.fetchurl
            {
              url = "https://ocaml.janestreet.com/ocaml-core/v0.16/files/ppx_globalize-v0.16.0.tar.gz";
              sha256 = "06s9mfcknbjvsjfgklhizd508zq0vz559lvxn5s2j4b5nysdfs4h";
            };
          opamInputs =
            {
              inherit (selection) ppxlib ocaml dune base;
            };
          opamSrc = repoPath (repos.opam-repository.src)
            {
              package = "packages/ppx_globalize/ppx_globalize.v0.16.0";
              hash = "sha256:0s8z4i3cmzcj01amvc1y5q4zd0fy1r46zl20gk8k38by9jvwcy5f";
            };
        };
      ppx_hash =
        {
          pname = "ppx_hash";
          version = "v0.16.0";
          src = pkgs.fetchurl
            {
              url = "https://ocaml.janestreet.com/ocaml-core/v0.16/files/ppx_hash-v0.16.0.tar.gz";
              sha256 = "1rdn2fzsqjdzx53smn20afxix8c8vav2z03gagyqn9xrnx32a0cv";
            };
          opamInputs =
            {
              inherit (selection) ppxlib ppx_sexp_conv ppx_compare ocaml dune base;
            };
          opamSrc = repoPath (repos.opam-repository.src)
            {
              package = "packages/ppx_hash/ppx_hash.v0.16.0";
              hash = "sha256:0fnqs0xg08r3g9gx9g90gxqxzgncv2383659xdw54dbs604ks6pc";
            };
        };
      ppx_here =
        {
          pname = "ppx_here";
          version = "v0.16.0";
          src = pkgs.fetchurl
            {
              url = "https://ocaml.janestreet.com/ocaml-core/v0.16/files/ppx_here-v0.16.0.tar.gz";
              sha256 = "1w3kjbnp16ypipfracpb0gr7imk4wbnks7j1ngx0dhq04nwri097";
            };
          opamInputs =
            {
              inherit (selection) ppxlib ocaml dune base;
            };
          opamSrc = repoPath (repos.opam-repository.src)
            {
              package = "packages/ppx_here/ppx_here.v0.16.0";
              hash = "sha256:044jv9sjivymm51lrg1p3hnnkp0rhjvi492jqviagarhimwmxlb2";
            };
        };
      ppx_ignore_instrumentation =
        {
          pname = "ppx_ignore_instrumentation";
          version = "v0.16.0";
          src = pkgs.fetchurl
            {
              url = "https://ocaml.janestreet.com/ocaml-core/v0.16/files/ppx_ignore_instrumentation-v0.16.0.tar.gz";
              sha256 = "01ckf16dmvkl9xzdwash610w4wn0k412dsmmb0k8201k47pm0bsj";
            };
          opamInputs =
            {
              inherit (selection) ppxlib ocaml dune;
            };
          opamSrc = repoPath (repos.opam-repository.src)
            {
              package = "packages/ppx_ignore_instrumentation/ppx_ignore_instrumentation.v0.16.0";
              hash = "sha256:13v8rmad322b650zwgvs6qfb1jmw2cx5a5lrbpzxy0x5s7371k0h";
            };
        };
      ppx_inline_test =
        {
          pname = "ppx_inline_test";
          version = "v0.16.1";
          src = pkgs.fetchurl
            {
              url = "https://github.com/janestreet/ppx_inline_test/archive/refs/tags/v0.16.1.tar.gz";
              sha256 = "0p99wi0vrk1kn62a0i0qw7gj3bwfw51gclj7j1s6gmr90pjn2kpa";
            };
          opamInputs =
            {
              inherit (selection) time_now ppxlib ocaml dune base;
            };
          opamSrc = repoPath (repos.opam-repository.src)
            {
              package = "packages/ppx_inline_test/ppx_inline_test.v0.16.1";
              hash = "sha256:00w5ndn3cbc3ma4k3c24lk596ds64ykk9jm9phzfwqfjsw97vbr1";
            };
        };
      ppx_jane =
        {
          pname = "ppx_jane";
          version = "v0.16.0";
          src = pkgs.fetchurl
            {
              url = "https://ocaml.janestreet.com/ocaml-core/v0.16/files/ppx_jane-v0.16.0.tar.gz";
              sha256 = "0cy1a6ckl81a7v6x57s08n042iz34zx46zwjns1bx2z3s8fv0lwx";
            };
          opamInputs =
            {
              inherit (selection) ppxlib ppx_variants_conv ppx_typerep_conv
                ppx_tydi ppx_string ppx_stable_witness ppx_stable ppx_sexp_value
                ppx_sexp_message ppx_pipebang ppx_optional ppx_module_timer ppx_log
                ppx_let ppx_inline_test ppx_ignore_instrumentation ppx_here
                ppx_fixed_literal ppx_fields_conv ppx_expect
                ppx_disable_unused_warnings ppx_custom_printf ppx_bin_prot ppx_bench
                ppx_base ppx_assert ocaml dune base_quickcheck;
            };
          opamSrc = repoPath (repos.opam-repository.src)
            {
              package = "packages/ppx_jane/ppx_jane.v0.16.0";
              hash = "sha256:0nl20vq579jc0jaadx101dkrn0yrw3vsvgnqqgdx0r22gbfizrl3";
            };
        };
      ppx_let =
        {
          pname = "ppx_let";
          version = "v0.16.0";
          src = pkgs.fetchurl
            {
              url = "https://ocaml.janestreet.com/ocaml-core/v0.16/files/ppx_let-v0.16.0.tar.gz";
              sha256 = "0p76id6wlkjpnypfxmzdx073c2hgf6k0q6vqps3sxw7l00qznjig";
            };
          opamInputs =
            {
              inherit (selection) ppxlib ppx_here ocaml dune base;
            };
          opamSrc = repoPath (repos.opam-repository.src)
            {
              package = "packages/ppx_let/ppx_let.v0.16.0";
              hash = "sha256:0g561g7b5xki84c5yzvy5r2f1m0sbqanhkry6787165mmp9j6984";
            };
        };
      ppx_log =
        {
          pname = "ppx_log";
          version = "v0.16.0";
          src = pkgs.fetchurl
            {
              url = "https://ocaml.janestreet.com/ocaml-core/v0.16/files/ppx_log-v0.16.0.tar.gz";
              sha256 = "1y7sfhfkq7i0b4pk3q1zc4d4m6l1wqrkxlk9s984w7jzgnr2mncl";
            };
          opamInputs =
            {
              inherit (selection) sexplib ppxlib ppx_sexp_message ppx_sexp_conv
                ppx_here ocaml dune base;
            };
          opamSrc = repoPath (repos.opam-repository.src)
            {
              package = "packages/ppx_log/ppx_log.v0.16.0";
              hash = "sha256:1zwhvl6j6im7zy4wv6lb4x7i0hn0xl9hfv6adzxr0900jk0ljr4g";
            };
        };
      ppx_module_timer =
        {
          pname = "ppx_module_timer";
          version = "v0.16.0";
          src = pkgs.fetchurl
            {
              url = "https://ocaml.janestreet.com/ocaml-core/v0.16/files/ppx_module_timer-v0.16.0.tar.gz";
              sha256 = "0x0zyk75n4icca8g60ks6xnfj533gi7jqni4ial7hcywqfz6xvia";
            };
          opamInputs =
            {
              inherit (selection) time_now stdio ppxlib ppx_base ocaml dune base;
            };
          opamSrc = repoPath (repos.opam-repository.src)
            {
              package = "packages/ppx_module_timer/ppx_module_timer.v0.16.0";
              hash = "sha256:00r1xk37k62yckvkf61lgh6dr1587g3qyg9pmzi8wi2dbd97mx6a";
            };
        };
      ppx_optcomp =
        {
          pname = "ppx_optcomp";
          version = "v0.16.0";
          src = pkgs.fetchurl
            {
              url = "https://ocaml.janestreet.com/ocaml-core/v0.16/files/ppx_optcomp-v0.16.0.tar.gz";
              sha256 = "18hbb7nmvrlnsmr6i2l9pyv2mav1jsbjicf6wkydlxak9840kclr";
            };
          opamInputs =
            {
              inherit (selection) stdio ppxlib ocaml dune base;
            };
          opamSrc = repoPath (repos.opam-repository.src)
            {
              package = "packages/ppx_optcomp/ppx_optcomp.v0.16.0";
              hash = "sha256:1yx4r9qhbzm1rx5r9w1490p83z4n1hfjbqg3nnp249g9n83x218w";
            };
        };
      ppx_optional =
        {
          pname = "ppx_optional";
          version = "v0.16.0";
          src = pkgs.fetchurl
            {
              url = "https://ocaml.janestreet.com/ocaml-core/v0.16/files/ppx_optional-v0.16.0.tar.gz";
              sha256 = "1axzphci4md8javp2bf1imh5zr19yj59hlwjnsfs6jywjiklzybh";
            };
          opamInputs =
            {
              inherit (selection) ppxlib ocaml dune base;
            };
          opamSrc = repoPath (repos.opam-repository.src)
            {
              package = "packages/ppx_optional/ppx_optional.v0.16.0";
              hash = "sha256:0fzxn8bbci4sjc7a6afp1pvz88jq52alq26vcpl2wxq6nbl296li";
            };
        };
      ppx_pipebang =
        {
          pname = "ppx_pipebang";
          version = "v0.16.0";
          src = pkgs.fetchurl
            {
              url = "https://ocaml.janestreet.com/ocaml-core/v0.16/files/ppx_pipebang-v0.16.0.tar.gz";
              sha256 = "0rps3vj6gbq595x3z90qcpngn8k5gc6ys0b4ysq5zifvkkj4gr5r";
            };
          opamInputs =
            {
              inherit (selection) ppxlib ocaml dune;
            };
          opamSrc = repoPath (repos.opam-repository.src)
            {
              package = "packages/ppx_pipebang/ppx_pipebang.v0.16.0";
              hash = "sha256:0xkv8ixkbsghvqavjm616npcachxc0yj72f9i1ccsvnspsr3pa27";
            };
        };
      ppx_sexp_conv =
        {
          pname = "ppx_sexp_conv";
          version = "v0.16.0";
          src = pkgs.fetchurl
            {
              url = "https://ocaml.janestreet.com/ocaml-core/v0.16/files/ppx_sexp_conv-v0.16.0.tar.gz";
              sha256 = "0390j76ins0hwxn4735ci2j2irgdphfszgq8hi151prvnfivgg21";
            };
          opamInputs =
            {
              inherit (selection) sexplib0 ppxlib ocaml dune base;
            };
          opamSrc = repoPath (repos.opam-repository.src)
            {
              package = "packages/ppx_sexp_conv/ppx_sexp_conv.v0.16.0";
              hash = "sha256:14ldpz4hcqbssgcy38h2i2fghw2f2y0m94fb5rjqzsmfy4n2v4yi";
            };
        };
      ppx_sexp_message =
        {
          pname = "ppx_sexp_message";
          version = "v0.16.0";
          src = pkgs.fetchurl
            {
              url = "https://ocaml.janestreet.com/ocaml-core/v0.16/files/ppx_sexp_message-v0.16.0.tar.gz";
              sha256 = "0f3xlhq4wcmdkmmqwiv7lvshs6q6fxvihx3vd2s340k7r0fr6a8q";
            };
          opamInputs =
            {
              inherit (selection) ppxlib ppx_sexp_conv ppx_here ocaml dune base;
            };
          opamSrc = repoPath (repos.opam-repository.src)
            {
              package = "packages/ppx_sexp_message/ppx_sexp_message.v0.16.0";
              hash = "sha256:1w8y1ma0zkl8mw4w76m7x74cwggpk3jjq4lwia13kzmrc66w4mcj";
            };
        };
      ppx_sexp_value =
        {
          pname = "ppx_sexp_value";
          version = "v0.16.0";
          src = pkgs.fetchurl
            {
              url = "https://ocaml.janestreet.com/ocaml-core/v0.16/files/ppx_sexp_value-v0.16.0.tar.gz";
              sha256 = "0sfk65v00p10xj1jjga2zcy6z758s28zmbmwsfvjnn7j9id03m3l";
            };
          opamInputs =
            {
              inherit (selection) ppxlib ppx_sexp_conv ppx_here ocaml dune base;
            };
          opamSrc = repoPath (repos.opam-repository.src)
            {
              package = "packages/ppx_sexp_value/ppx_sexp_value.v0.16.0";
              hash = "sha256:0kyw1m4zm4nnmjm710pss27wkpbfkg99sdsbhrz7067dlbli83fj";
            };
        };
      ppx_stable =
        {
          pname = "ppx_stable";
          version = "v0.16.0";
          src = pkgs.fetchurl
            {
              url = "https://ocaml.janestreet.com/ocaml-core/v0.16/files/ppx_stable-v0.16.0.tar.gz";
              sha256 = "151h2z1a1b62hl3jjr8y6j88hgm7gvx7mjzpv0i4kjb20rafgf4i";
            };
          opamInputs =
            {
              inherit (selection) ppxlib ocaml dune base;
            };
          opamSrc = repoPath (repos.opam-repository.src)
            {
              package = "packages/ppx_stable/ppx_stable.v0.16.0";
              hash = "sha256:1kaicvjacysz47wz8gba2imbd5x9c3m2fd7v98jn2f9ad4l2zzp3";
            };
        };
      ppx_stable_witness =
        {
          pname = "ppx_stable_witness";
          version = "v0.16.0";
          src = pkgs.fetchurl
            {
              url = "https://ocaml.janestreet.com/ocaml-core/v0.16/files/ppx_stable_witness-v0.16.0.tar.gz";
              sha256 = "1vy5g2md1mi9r28rxwlxbcnjwiqrdaa0p56q9f2c6rcx5mhmg62g";
            };
          opamInputs =
            {
              inherit (selection) ppxlib ocaml dune base;
            };
          opamSrc = repoPath (repos.opam-repository.src)
            {
              package = "packages/ppx_stable_witness/ppx_stable_witness.v0.16.0";
              hash = "sha256:0f2j5762l3mnwrzghg7rir6ay566bdwcr9yg8rq7y3330fpsnkvw";
            };
        };
      ppx_string =
        {
          pname = "ppx_string";
          version = "v0.16.0";
          src = pkgs.fetchurl
            {
              url = "https://ocaml.janestreet.com/ocaml-core/v0.16/files/ppx_string-v0.16.0.tar.gz";
              sha256 = "0dl32hfiajs2xyapy3b1zsd82risb5pfp4xlzrkbdvm88sa9jnqz";
            };
          opamInputs =
            {
              inherit (selection) ppxlib ppx_base ocaml dune base;
            };
          opamSrc = repoPath (repos.opam-repository.src)
            {
              package = "packages/ppx_string/ppx_string.v0.16.0";
              hash = "sha256:0ns03rz4lrfq0wgg42y14zvgndhm1lzqk852a3l6h71i38nkdygw";
            };
        };
      ppx_tydi =
        {
          pname = "ppx_tydi";
          version = "v0.16.0";
          src = pkgs.fetchurl
            {
              url = "https://ocaml.janestreet.com/ocaml-core/v0.16/files/ppx_tydi-v0.16.0.tar.gz";
              sha256 = "1ijswarkiczz0z9khahmr70np91xn2sskp11jdw5pcsq3wx1aqx3";
            };
          opamInputs =
            {
              inherit (selection) ppxlib ocaml dune base;
            };
          opamSrc = repoPath (repos.opam-repository.src)
            {
              package = "packages/ppx_tydi/ppx_tydi.v0.16.0";
              hash = "sha256:0gx8p3w9kr2x39slrg6kvr75wlfv713zs85nba402zg72cgkdr46";
            };
        };
      ppx_typerep_conv =
        {
          pname = "ppx_typerep_conv";
          version = "v0.16.0";
          src = pkgs.fetchurl
            {
              url = "https://ocaml.janestreet.com/ocaml-core/v0.16/files/ppx_typerep_conv-v0.16.0.tar.gz";
              sha256 = "16hd1xwag5qgdrwhbbmdngnm6h9vnflcvh1qgv2vknrhggp6bmgz";
            };
          opamInputs =
            {
              inherit (selection) typerep ppxlib ocaml dune base;
            };
          opamSrc = repoPath (repos.opam-repository.src)
            {
              package = "packages/ppx_typerep_conv/ppx_typerep_conv.v0.16.0";
              hash = "sha256:0cf3y6ipk6hgmr52lhqzs28z9wc2i8vjklzkd87dkild4z3vm6a8";
            };
        };
      ppx_variants_conv =
        {
          pname = "ppx_variants_conv";
          version = "v0.16.0";
          src = pkgs.fetchurl
            {
              url = "https://ocaml.janestreet.com/ocaml-core/v0.16/files/ppx_variants_conv-v0.16.0.tar.gz";
              sha256 = "1r45d34jwdwa3893mvd1as7lh5j68g75nx6h3anynqbnpwsi1ar0";
            };
          opamInputs =
            {
              inherit (selection) variantslib ppxlib ocaml dune base;
            };
          opamSrc = repoPath (repos.opam-repository.src)
            {
              package = "packages/ppx_variants_conv/ppx_variants_conv.v0.16.0";
              hash = "sha256:0ckn6xyic32mhn58hdj5505x30fw5v5pixx9wshix6fwwjmzs4kc";
            };
        };
      ppxlib =
        {
          pname = "ppxlib";
          version = "0.31.0";
          src = pkgs.fetchurl
            {
              url = "https://github.com/ocaml-ppx/ppxlib/releases/download/0.31.0/ppxlib-0.31.0.tbz";
              sha256 = "1n21msr5a6l7j4j1bkzgcqfm4r1vf3lgzjlmg0ns3yjp9rjpc5nj";
            };
          opamInputs =
            {
              inherit (selection) stdlib-shims sexplib0 ppx_derivers
                ocaml-compiler-libs ocaml dune;
            };
          opamSrc = repoPath (repos.opam-repository.src)
            {
              package = "packages/ppxlib/ppxlib.0.31.0";
              hash = "sha256:0blfx47zi85l729wwm9day7rij78lqyi6ddznkmb9w84f1vhac19";
            };
        };
      prettym =
        {
          pname = "prettym";
          version = "0.0.3";
          src = pkgs.fetchurl
            {
              url = "https://github.com/dinosaure/prettym/releases/download/0.0.3/prettym-0.0.3.tbz";
              sha256 = "02cgp4c6pd1i8f4pavhwjxgl34bbpd9bx9c4lnc4szyy3ahz2w4i";
            };
          opamInputs =
            {
              inherit (selection) ocaml ke fmt dune bigstringaf bigarray-overlap;
            };
          opamSrc = repoPath (repos.opam-repository.src)
            {
              package = "packages/prettym/prettym.0.0.3";
              hash = "sha256:188vz3z2k2k3xn5v00jgwv0asi8k9ihd14ksd639lllg4s2cmh1z";
            };
        };
      psq =
        {
          pname = "psq";
          version = "0.2.1";
          src = pkgs.fetchurl
            {
              url = "https://github.com/pqwy/psq/releases/download/v0.2.1/psq-0.2.1.tbz";
              sha256 = "0i6k5i3dha3b4syz4jpd5fi6dkalas8bhcpfk4blprxb7r9my022";
            };
          opamInputs = {
            inherit (selection) seq ocaml dune;
          };
          opamSrc = repoPath (repos.opam-repository.src)
            {
              package = "packages/psq/psq.0.2.1";
              hash = "sha256:02q8kpskr8ci5h4wbq14m9qr2a1vjk4zivfhi79gnfp8jl92hdyl";
            };
        };
      ptime =
        {
          pname = "ptime";
          version = "1.1.0";
          src = pkgs.fetchurl
            {
              url = "https://erratique.ch/software/ptime/releases/ptime-1.1.0.tbz";
              sha256 = "1c9y07vnvllfprf0z1vqf6fr73qxw7hj6h1k5ig109zvaiab3xfb";
            };
          opamInputs =
            {
              inherit (selection) topkg ocamlfind ocamlbuild ocaml;
            };
          opamSrc = repoPath (repos.opam-repository.src)
            {
              package = "packages/ptime/ptime.1.1.0";
              hash = "sha256:0a6ga17zw5h31107bc47r37mr31dwxnji1c39xx558w39c1avp7p";
            };
        };
      re =
        {
          pname = "re";
          version = "1.11.0";
          src = pkgs.fetchurl
            {
              url = "https://github.com/ocaml/ocaml-re/releases/download/1.11.0/re-1.11.0.tbz";
              sha256 = "0kwdvzb2wy3rxq3mvmsgc8cdwrzka2viysvrmrrbxxn0h13j9z01";
            };
          opamInputs = {
            inherit (selection) seq ocaml dune;
          };
          opamSrc = repoPath (repos.opam-repository.src)
            {
              package = "packages/re/re.1.11.0";
              hash = "sha256:18048c9lw3g8db1r01diljzvla2pj9bw2fcnvq34gnviwi9rxqjf";
            };
        };
      result =
        {
          pname = "result";
          version = "1.5";
          src = pkgs.fetchurl
            {
              url = "https://github.com/janestreet/result/releases/download/1.5/result-1.5.tbz";
              sha256 = "0cpfp35fdwnv3p30a06wd0py3805qxmq3jmcynjc3x2qhlimwfkw";
            };
          opamInputs = {
            inherit (selection) ocaml dune;
          };
          opamSrc = repoPath (repos.opam-repository.src)
            {
              package = "packages/result/result.1.5";
              hash = "sha256:0ybmvlisfz5swvbcq855czz1ysv9zxmb79f1m0x8284hczmfm98f";
            };
        };
      rresult =
        {
          pname = "rresult";
          version = "0.7.0";
          src = pkgs.fetchurl
            {
              url = "https://erratique.ch/software/rresult/releases/rresult-0.7.0.tbz";
              sha256 = "0h2mjyzhay1p4k7n0mzaa7hlc7875kiy6m1i3r1n03j6hddpzahi";
            };
          opamInputs =
            {
              inherit (selection) topkg ocamlfind ocamlbuild ocaml;
            };
          opamSrc = repoPath (repos.opam-repository.src)
            {
              package = "packages/rresult/rresult.0.7.0";
              hash = "sha256:0131az6qj1086hi1kjc7x99x1q4c0z3axjwd1wbmr6c6r6nnaj6y";
            };
        };
      seq =
        {
          pname = "seq";
          version = "base";
          src = null;
          opamInputs = {
            inherit (selection) ocaml;
          };
          opamSrc = repoPath (repos.opam-repository.src)
            {
              package = "packages/seq/seq.base";
              hash = "sha256:1vm8mk6zm2q3fwnkprl6jib048zr4ysldw0bl74x6wwbxj0vx6k9";
            };
        };
      sexplib =
        {
          pname = "sexplib";
          version = "v0.16.0";
          src = pkgs.fetchurl
            {
              url = "https://ocaml.janestreet.com/ocaml-core/v0.16/files/sexplib-v0.16.0.tar.gz";
              sha256 = "0nxc47d9szcxs3vfqfzfxylcpihjza4lwjynbyx18wqmrb8xar75";
            };
          opamInputs =
            {
              inherit (selection) sexplib0 parsexp ocaml num dune;
            };
          opamSrc = repoPath (repos.opam-repository.src)
            {
              package = "packages/sexplib/sexplib.v0.16.0";
              hash = "sha256:19x1c3s6nnj6vk3yil4a4vj8ylzv7v2nk89rpa344jjijq41cvj2";
            };
        };
      sexplib0 =
        {
          pname = "sexplib0";
          version = "v0.16.0";
          src = pkgs.fetchurl
            {
              url = "https://ocaml.janestreet.com/ocaml-core/v0.16/files/sexplib0-v0.16.0.tar.gz";
              sha256 = "07bhj2akd6i33h11qin4wns9qnjicf871yzji7vi4i8rd1ja5nw6";
            };
          opamInputs = {
            inherit (selection) ocaml dune;
          };
          opamSrc = repoPath (repos.opam-repository.src)
            {
              package = "packages/sexplib0/sexplib0.v0.16.0";
              hash = "sha256:11zmpbm8pj86dmc2fgbz33ngqs1a854dgsayq24hzlvdvif5bgqw";
            };
        };
      splittable_random =
        {
          pname = "splittable_random";
          version = "v0.16.0";
          src = pkgs.fetchurl
            {
              url = "https://ocaml.janestreet.com/ocaml-core/v0.16/files/splittable_random-v0.16.0.tar.gz";
              sha256 = "1lzn3w92vw8z93r29s5vwps16gl0pyz3f84zwf6c3qq37w31nvz1";
            };
          opamInputs =
            {
              inherit (selection) ppx_sexp_message ppx_inline_test ppx_bench
                ppx_assert ocaml dune base;
            };
          opamSrc = repoPath (repos.opam-repository.src)
            {
              package = "packages/splittable_random/splittable_random.v0.16.0";
              hash = "sha256:1ba9v817315f4pnvm6ssr37k8vibs7s1mg4vafg8n8dd917h9l73";
            };
        };
      ssl =
        {
          pname = "ssl";
          version = "0.7.0";
          src = pkgs.fetchurl
            {
              url = "https://github.com/savonet/ocaml-ssl/archive/refs/tags/v0.7.0.tar.gz";
              sha256 = "1bgs3snm6sks5a496h4gkj8xqmayrf3prfhwpxd3xp70rr92dhgg";
            };
          opamInputs =
            {
              inherit (selection) ocaml dune-configurator dune conf-libssl;
            };
          opamSrc = repoPath (repos.opam-repository.src)
            {
              package = "packages/ssl/ssl.0.7.0";
              hash = "sha256:1zg7lw8z6bqjz4w5yjw4g5ijb1zxdb5rxp8vpk23dd9mdg4wsm2i";
            };
        };
      stdio =
        {
          pname = "stdio";
          version = "v0.16.0";
          src = pkgs.fetchurl
            {
              url = "https://ocaml.janestreet.com/ocaml-core/v0.16/files/stdio-v0.16.0.tar.gz";
              sha256 = "0gm7nci6bi3gfc5q3m8rv4138ip6rhidih3fihvwajk1a1cvgw31";
            };
          opamInputs = {
            inherit (selection) ocaml dune base;
          };
          opamSrc = repoPath (repos.opam-repository.src)
            {
              package = "packages/stdio/stdio.v0.16.0";
              hash = "sha256:029985vdqfj1xavwdrhd2kgs8pkfdfkf39bb90fb3ap180fqfw81";
            };
        };
      stdlib-shims =
        {
          pname = "stdlib-shims";
          version = "0.3.0";
          src = pkgs.fetchurl
            {
              url = "https://github.com/ocaml/stdlib-shims/releases/download/0.3.0/stdlib-shims-0.3.0.tbz";
              sha256 = "0jnqsv6pqp5b5g7lcjwgd75zqqvcwcl5a32zi03zg1kvj79p5gxs";
            };
          opamInputs = {
            inherit (selection) ocaml dune;
          };
          opamSrc = repoPath (repos.opam-repository.src)
            {
              package = "packages/stdlib-shims/stdlib-shims.0.3.0";
              hash = "sha256:1hwyzzcx7clz4p58fj3n6frq2srbxdmhmxxd6n6mpw9gj2vs6yiw";
            };
        };
      stringext =
        {
          pname = "stringext";
          version = "1.6.0";
          src = pkgs.fetchurl
            {
              url = "https://github.com/rgrinberg/stringext/releases/download/1.6.0/stringext-1.6.0.tbz";
              sha256 = "1sh6nafi3i9773j5mlwwz3kxfzdjzsfqj2qibxhigawy5vazahfv";
            };
          opamInputs = {
            inherit (selection) ocaml dune;
          };
          opamSrc = repoPath (repos.opam-repository.src)
            {
              package = "packages/stringext/stringext.1.6.0";
              hash = "sha256:01k5gspcs4i7ipghzm2qsxgmyja86nd224achciny46xdjpkchpd";
            };
        };
      time_now =
        {
          pname = "time_now";
          version = "v0.16.0";
          src = pkgs.fetchurl
            {
              url = "https://ocaml.janestreet.com/ocaml-core/v0.16/files/time_now-v0.16.0.tar.gz";
              sha256 = "18f3dpafs7pj07wnymyhrpp6kzhx1jya5r3ni6xyvap6vsm8982z";
            };
          opamInputs =
            {
              inherit (selection) ppx_optcomp ppx_base ocaml jst-config
                jane-street-headers dune base;
            };
          opamSrc = repoPath (repos.opam-repository.src)
            {
              package = "packages/time_now/time_now.v0.16.0";
              hash = "sha256:1znd8q9s42jsplz0xrlrvq838q0pia6qp6m5kj48gnsd22c1zfxd";
            };
        };
      topkg =
        {
          pname = "topkg";
          version = "1.0.7";
          src = pkgs.fetchurl
            {
              url = "https://erratique.ch/software/topkg/releases/topkg-1.0.7.tbz";
              sha256 = "06dya9n5im3dbqqv4l6yssi8siw111c1hp94n5y14vddyg9jmhjz";
            };
          opamInputs =
            {
              inherit (selection) ocamlfind ocamlbuild ocaml;
            };
          opamSrc = repoPath (repos.opam-repository.src)
            {
              package = "packages/topkg/topkg.1.0.7";
              hash = "sha256:1411142m653308lj3nlgbv2wvww2i5hyfdgz94l2b3ga3qdp7szc";
            };
        };
      typerep =
        {
          pname = "typerep";
          version = "v0.16.0";
          src = pkgs.fetchurl
            {
              url = "https://ocaml.janestreet.com/ocaml-core/v0.16/files/typerep-v0.16.0.tar.gz";
              sha256 = "0b7pshp8f7k97m690ik0x2gbasj1jfxpfmhsy2n9s8p0c7ppy5g5";
            };
          opamInputs = {
            inherit (selection) ocaml dune base;
          };
          opamSrc = repoPath (repos.opam-repository.src)
            {
              package = "packages/typerep/typerep.v0.16.0";
              hash = "sha256:0lnvr8avqj50p2hp4y85j0492dv7c2dyp7mf28fvjab8c3nw6h4a";
            };
        };
      tyxml =
        {
          pname = "tyxml";
          version = "4.6.0";
          src = pkgs.fetchurl
            {
              url = "https://github.com/ocsigen/tyxml/releases/download/4.6.0/tyxml-4.6.0.tbz";
              sha256 = "1p82r68lxk6wzxihzd620a6kzp27vn548j2cr970l4jfdcy6gsxz";
            };
          opamInputs =
            {
              inherit (selection) uutf seq re ocaml dune;
            };
          opamSrc = repoPath (repos.opam-repository.src)
            {
              package = "packages/tyxml/tyxml.4.6.0";
              hash = "sha256:02pnpfr487d077arnvras1a6p52san6l5xkw0adgaxqpi7cf1cqy";
            };
        };
      unstrctrd =
        {
          pname = "unstrctrd";
          version = "0.3";
          src = pkgs.fetchurl
            {
              url = "https://github.com/dinosaure/unstrctrd/releases/download/v0.3/unstrctrd-v0.3.tbz";
              sha256 = "0nzdinks5j5drk3ihj0p9vv9wc7zdw9rz3y886360xxrlvlv2mbk";
            };
          opamInputs =
            {
              inherit (selection) uutf ocaml dune angstrom;
            };
          opamSrc = repoPath (repos.opam-repository.src)
            {
              package = "packages/unstrctrd/unstrctrd.0.3";
              hash = "sha256:1r3j78vy4lvyng6b3ljxfp23z0cmajljwxsx8yddl00dbgaidwnl";
            };
        };
      uri =
        {
          pname = "uri";
          version = "4.4.0";
          src = pkgs.fetchurl
            {
              url = "https://github.com/mirage/ocaml-uri/releases/download/v4.4.0/uri-4.4.0.tbz";
              sha256 = "1i6ygbqnn6wf6cp015jfkw5biv3899p4rdy7kkjn28fdympazayd";
            };
          opamInputs =
            {
              inherit (selection) stringext ocaml dune angstrom;
            };
          opamSrc = repoPath (repos.opam-repository.src)
            {
              package = "packages/uri/uri.4.4.0";
              hash = "sha256:1jzwbdw5lp3bv1hw9kdi86d0yzzfg5shp0571kw9gkhypisr7jva";
            };
        };
      uutf =
        {
          pname = "uutf";
          version = "1.0.3";
          src = pkgs.fetchurl
            {
              url = "https://erratique.ch/software/uutf/releases/uutf-1.0.3.tbz";
              sha256 = "0s05r8ggp1g97zq4rnvbxzj22pv8ld0k5wsdw662jw0y7mhsawl7";
            };
          opamInputs =
            {
              inherit (selection) topkg ocamlfind ocamlbuild
                ocaml;
              cmdliner = selection.cmdliner or null;
            };
          opamSrc = repoPath (repos.opam-repository.src)
            {
              package = "packages/uutf/uutf.1.0.3";
              hash = "sha256:1x57h3bc68rsm2kd18wjbkfjk67shak6jgplp7paw97faqgmgx3x";
            };
        };
      variantslib =
        {
          pname = "variantslib";
          version = "v0.16.0";
          src = pkgs.fetchurl
            {
              url = "https://ocaml.janestreet.com/ocaml-core/v0.16/files/variantslib-v0.16.0.tar.gz";
              sha256 = "0brpknl9ckkn0m2whlkczg9r33z6057sgh1wkk262f0jpk87mbi7";
            };
          opamInputs = {
            inherit (selection) ocaml dune base;
          };
          opamSrc = repoPath (repos.opam-repository.src)
            {
              package = "packages/variantslib/variantslib.v0.16.0";
              hash = "sha256:1xiwyyjzdlsyqc1889q24qzr5f67f8cjv1vq3wydhm2hr73i2ykd";
            };
        };
      yojson =
        {
          pname = "yojson";
          version = "2.1.1";
          src = pkgs.fetchurl
            {
              url = "https://github.com/ocaml-community/yojson/releases/download/2.1.1/yojson-2.1.1.tbz";
              sha256 = "0ww1x289g01qb8bw9nf077hzjd2c0xp0cfb2hrjw138rgch870fm";
            };
          opamInputs =
            {
              inherit (selection) seq ocaml dune cppo;
            };
          opamSrc = repoPath (repos.opam-repository.src)
            {
              package = "packages/yojson/yojson.2.1.1";
              hash = "sha256:0vgzzgkvnmyny76658iyf3n6d7z1d3w1gqcwbqh6my1vbn2b3s5h";
            };
        };
    };
}

